name: bdaya_shared_value
description: A straightforward way to manage global state in flutter apps.
version: 4.0.0
homepage: https://github.com/Bdaya-Dev/flutter-shared-value
repository: https://github.com/Bdaya-Dev/flutter-shared-value

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
