name: bdaya_shared_value
description: A straightforward way to manage global state in flutter apps.
version: 3.1.3
homepage: https://github.com/Bdaya-Dev/flutter-shared-value

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.27.5
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
